---
- hosts: webserver
  gather_facts: true
  user: ubuntu
  sudo: True
  tasks:

    # fetch instance data from the metadata servers in ec2
    - ec2_facts:

    # just show the instance-id
    - debug: msg= "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"

- hosts: webserver 
  gather_facts: True
  connection: local
  vars:
    region: "us-east-1"
  tasks:
    - name: destroy all instances
      ec2: state='absent'
           region={{ region }}
           instance_ids={{ item }}
           wait=true
      with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']

